[[redirects]]
  from = "http://respal.netlify.com/*"
  to = "http://res.palash.tk/:splat"
  status = 301
  
[[redirects]]
  from = "https://respal.netlify.com/*"
  to = "https://res.palash.tk/:splat"
  status = 301  
